### ISSUE TITLE
Main.css

### ISSUE THREAD

**Issue by UniMishka** [UniMishka/WebProject#6]
Ссылка на сайт: http://regions.ru/
Желательно сделать скриншот, потому что новости меняются, чтобы делать одну страницу с обной информацией
повторить полностью
Скрин закину в беседу
В ответе пусть отпишется только один, тот кто будет делать main

**Comment by Shayrma749506887** [comment]
Сделал скриншоты сайта

**Comment by Shayrma749506887** [comment]
Что дальше???
